<html>
<head></head>
<body>
<p hidden>&nbsp;</p>
<p style="font: 16px/25.6px &quot;Helvetica Neue&quot;, Helvetica, &quot;Hiragino Sans GB&quot;, &quot;Microsoft YaHei&quot;, Arial, sans-serif; margin: 0px; padding: 0px; text-align: center; color: rgb(62, 62, 62); text-transform: none; text-indent: 0px; letter-spacing: normal; clear: both; word-spacing: 0px; white-space: normal; -ms-word-wrap: break-word !important; min-height: 1em; max-width: 100%; box-sizing: border-box !important; widows: 1; font-size-adjust: none; font-stretch: normal; background-color: rgb(255, 255, 255); -webkit-text-stroke-width: 0px; overflow-wrap: break-word;">
    <span style="margin: 0px; padding: 0px; line-height: 19.2px; font-size: 13.33px; -ms-word-wrap: break-word !important; max-width: 100%; box-sizing: border-box !important; overflow-wrap: break-word;"
          hidden>&lt;最黑科技小站原创，转载请联系授权&gt;</span></p>
<hr style="font: 16px/25.6px &quot;Helvetica Neue&quot;, Helvetica, &quot;Hiragino Sans GB&quot;, &quot;Microsoft YaHei&quot;, Arial, sans-serif; margin: 0px; padding: 0px; color: rgb(62, 62, 62); text-transform: none; text-indent: 0px; letter-spacing: normal; word-spacing: 0px; white-space: normal; -ms-word-wrap: break-word !important; max-width: 100%; box-sizing: border-box !important; widows: 1; font-size-adjust: none; font-stretch: normal; background-color: rgb(255, 255, 255); -webkit-text-stroke-width: 0px; overflow-wrap: break-word;">
<p style="font: 16px/25.6px &quot;Helvetica Neue&quot;, Helvetica, &quot;Hiragino Sans GB&quot;, &quot;Microsoft YaHei&quot;, Arial, sans-serif; margin: 0px; padding: 0px; color: rgb(62, 62, 62); text-transform: none; text-indent: 0px; letter-spacing: normal; clear: both; word-spacing: 0px; white-space: normal; -ms-word-wrap: break-word !important; min-height: 1em; max-width: 100%; box-sizing: border-box !important; widows: 1; font-size-adjust: none; font-stretch: normal; background-color: rgb(255, 255, 255); -webkit-text-stroke-width: 0px; overflow-wrap: break-word;">
    <br style="margin: 0px; padding: 0px; -ms-word-wrap: break-word !important; max-width: 100%; box-sizing: border-box !important; overflow-wrap: break-word;">
</p>
<p style="font: 16px/25.6px &quot;Helvetica Neue&quot;, Helvetica, &quot;Hiragino Sans GB&quot;, &quot;Microsoft YaHei&quot;, Arial, sans-serif; margin: 0px; padding: 0px; text-align: center; color: rgb(62, 62, 62); text-transform: none; text-indent: 0px; letter-spacing: normal; clear: both; word-spacing: 0px; white-space: normal; -ms-word-wrap: break-word !important; min-height: 1em; max-width: 100%; box-sizing: border-box !important; widows: 1; font-size-adjust: none; font-stretch: normal; background-color: rgb(255, 255, 255); -webkit-text-stroke-width: 0px; overflow-wrap: break-word;">
    <span style="margin: 0px; padding: 0px; line-height: 25.6px; font-size: 14px; -ms-word-wrap: break-word !important; max-width: 100%; box-sizing: border-box !important; overflow-wrap: break-word;"
          hidden>孤独的话说太多，</span></p>
<p style="font: 16px/25.6px &quot;Helvetica Neue&quot;, Helvetica, &quot;Hiragino Sans GB&quot;, &quot;Microsoft YaHei&quot;, Arial, sans-serif; margin: 0px; padding: 0px; text-align: center; color: rgb(62, 62, 62); text-transform: none; text-indent: 0px; letter-spacing: normal; clear: both; word-spacing: 0px; white-space: normal; -ms-word-wrap: break-word !important; min-height: 1em; max-width: 100%; box-sizing: border-box !important; widows: 1; font-size-adjust: none; font-stretch: normal; background-color: rgb(255, 255, 255); -webkit-text-stroke-width: 0px; overflow-wrap: break-word;">
    <span style="margin: 0px; padding: 0px; line-height: 25.6px; font-size: 14px; -ms-word-wrap: break-word !important; max-width: 100%; box-sizing: border-box !important; overflow-wrap: break-word;"
          hidden>不被倾听更难过，</span></p>
<p style="font: 16px/25.6px &quot;Helvetica Neue&quot;, Helvetica, &quot;Hiragino Sans GB&quot;, &quot;Microsoft YaHei&quot;, Arial, sans-serif; margin: 0px; padding: 0px; text-align: center; color: rgb(62, 62, 62); text-transform: none; text-indent: 0px; letter-spacing: normal; clear: both; word-spacing: 0px; white-space: normal; -ms-word-wrap: break-word !important; min-height: 1em; max-width: 100%; box-sizing: border-box !important; widows: 1; font-size-adjust: none; font-stretch: normal; background-color: rgb(255, 255, 255); -webkit-text-stroke-width: 0px; overflow-wrap: break-word;">
    <span style="margin: 0px; padding: 0px; line-height: 25.6px; font-size: 14px; -ms-word-wrap: break-word !important; max-width: 100%; box-sizing: border-box !important; overflow-wrap: break-word;"
          hidden>现在有了微信、支付宝...</span></p>
<p style="font: 16px/25.6px &quot;Helvetica Neue&quot;, Helvetica, &quot;Hiragino Sans GB&quot;, &quot;Microsoft YaHei&quot;, Arial, sans-serif; margin: 0px; padding: 0px; text-align: center; color: rgb(62, 62, 62); text-transform: none; text-indent: 0px; letter-spacing: normal; clear: both; word-spacing: 0px; white-space: normal; -ms-word-wrap: break-word !important; min-height: 1em; max-width: 100%; box-sizing: border-box !important; widows: 1; font-size-adjust: none; font-stretch: normal; background-color: rgb(255, 255, 255); -webkit-text-stroke-width: 0px; overflow-wrap: break-word;">
    <span style="margin: 0px; padding: 0px; line-height: 25.6px; font-size: 14px; -ms-word-wrap: break-word !important; max-width: 100%; box-sizing: border-box !important; overflow-wrap: break-word;"
          hidden>钱包被遗忘了？</span></p>
<p style="font: 16px/25.6px &quot;Helvetica Neue&quot;, Helvetica, &quot;Hiragino Sans GB&quot;, &quot;Microsoft YaHei&quot;, Arial, sans-serif; margin: 0px; padding: 0px; text-align: center; color: rgb(62, 62, 62); text-transform: none; text-indent: 0px; letter-spacing: normal; clear: both; word-spacing: 0px; white-space: normal; -ms-word-wrap: break-word !important; min-height: 1em; max-width: 100%; box-sizing: border-box !important; widows: 1; font-size-adjust: none; font-stretch: normal; background-color: rgb(255, 255, 255); -webkit-text-stroke-width: 0px; overflow-wrap: break-word;">
    <img data-ratio="0.7359375" data-s="300,640" data-src="/ksyun/2017/03/04/4d1104c64865491ca1e20f3864a3deb4.jpeg"
         data-type="jpeg" data-w="640"
         style="margin: 0px; padding: 0px; width: auto !important; height: auto !important; visibility: visible !important; -ms-word-wrap: break-word !important; max-width: 100%; box-sizing: border-box !important; overflow-wrap: break-word;"
         src="http://static.poinetech.com/cms/ksyun/2017/03/04/4d1104c64865491ca1e20f3864a3deb4.jpeg" width="auto"
         hidden></p>
<p style="font: 16px/25.6px &quot;Helvetica Neue&quot;, Helvetica, &quot;Hiragino Sans GB&quot;, &quot;Microsoft YaHei&quot;, Arial, sans-serif; margin: 0px; padding: 0px; text-align: center; color: rgb(62, 62, 62); text-transform: none; text-indent: 0px; letter-spacing: normal; clear: both; word-spacing: 0px; white-space: normal; -ms-word-wrap: break-word !important; min-height: 1em; max-width: 100%; box-sizing: border-box !important; widows: 1; font-size-adjust: none; font-stretch: normal; background-color: rgb(255, 255, 255); -webkit-text-stroke-width: 0px; overflow-wrap: break-word;">
    <span style="margin: 0px; padding: 0px; line-height: 25.6px; font-size: 14px; -ms-word-wrap: break-word !important; max-width: 100%; box-sizing: border-box !important; overflow-wrap: break-word;"></span><span
        style="margin: 0px; padding: 0px; line-height: 25.6px; font-size: 14px; -ms-word-wrap: break-word !important; max-width: 100%; box-sizing: border-box !important; overflow-wrap: break-word;"><br
        style="margin: 0px; padding: 0px; -ms-word-wrap: break-word !important; max-width: 100%; box-sizing: border-box !important; overflow-wrap: break-word;"></span>
</p>
<p style="font: 16px/25.6px &quot;Helvetica Neue&quot;, Helvetica, &quot;Hiragino Sans GB&quot;, &quot;Microsoft YaHei&quot;, Arial, sans-serif; margin: 0px; padding: 0px; text-align: center; color: rgb(62, 62, 62); text-transform: none; text-indent: 0px; letter-spacing: normal; clear: both; word-spacing: 0px; white-space: normal; -ms-word-wrap: break-word !important; min-height: 1em; max-width: 100%; box-sizing: border-box !important; widows: 1; font-size-adjust: none; font-stretch: normal; background-color: rgb(255, 255, 255); -webkit-text-stroke-width: 0px; overflow-wrap: break-word;">
    <span style="margin: 0px; padding: 0px; line-height: 25.6px; font-size: 14px; -ms-word-wrap: break-word !important; max-width: 100%; box-sizing: border-box !important; overflow-wrap: break-word;"
          hidden>如今我放下了手机，</span></p>
<p style="font: 16px/25.6px &quot;Helvetica Neue&quot;, Helvetica, &quot;Hiragino Sans GB&quot;, &quot;Microsoft YaHei&quot;, Arial, sans-serif; margin: 0px; padding: 0px; text-align: center; color: rgb(62, 62, 62); text-transform: none; text-indent: 0px; letter-spacing: normal; clear: both; word-spacing: 0px; white-space: normal; -ms-word-wrap: break-word !important; min-height: 1em; max-width: 100%; box-sizing: border-box !important; widows: 1; font-size-adjust: none; font-stretch: normal; background-color: rgb(255, 255, 255); -webkit-text-stroke-width: 0px; overflow-wrap: break-word;">
    <span style="margin: 0px; padding: 0px; line-height: 25.6px; font-size: 14px; -ms-word-wrap: break-word !important; max-width: 100%; box-sizing: border-box !important; overflow-wrap: break-word;"
          hidden>放下了个性，</span></p>
<p style="font: 16px/25.6px &quot;Helvetica Neue&quot;, Helvetica, &quot;Hiragino Sans GB&quot;, &quot;Microsoft YaHei&quot;, Arial, sans-serif; margin: 0px; padding: 0px; text-align: center; color: rgb(62, 62, 62); text-transform: none; text-indent: 0px; letter-spacing: normal; clear: both; word-spacing: 0px; white-space: normal; -ms-word-wrap: break-word !important; min-height: 1em; max-width: 100%; box-sizing: border-box !important; widows: 1; font-size-adjust: none; font-stretch: normal; background-color: rgb(255, 255, 255); -webkit-text-stroke-width: 0px; overflow-wrap: break-word;">
    <span style="margin: 0px; padding: 0px; line-height: 25.6px; font-size: 14px; -ms-word-wrap: break-word !important; max-width: 100%; box-sizing: border-box !important; overflow-wrap: break-word;"
          hidden>放下了固执，</span></p>
<p style="font: 16px/25.6px &quot;Helvetica Neue&quot;, Helvetica, &quot;Hiragino Sans GB&quot;, &quot;Microsoft YaHei&quot;, Arial, sans-serif; margin: 0px; padding: 0px; text-align: center; color: rgb(62, 62, 62); text-transform: none; text-indent: 0px; letter-spacing: normal; clear: both; word-spacing: 0px; white-space: normal; -ms-word-wrap: break-word !important; min-height: 1em; max-width: 100%; box-sizing: border-box !important; widows: 1; font-size-adjust: none; font-stretch: normal; background-color: rgb(255, 255, 255); -webkit-text-stroke-width: 0px; overflow-wrap: break-word;">
    <span style="margin: 0px; padding: 0px; line-height: 25.6px; font-size: 14px; -ms-word-wrap: break-word !important; max-width: 100%; box-sizing: border-box !important; overflow-wrap: break-word;"
          hidden>都只是因为放不下一款已成精的智能钱包</span></p>
<p style="font: 16px/25.6px &quot;Helvetica Neue&quot;, Helvetica, &quot;Hiragino Sans GB&quot;, &quot;Microsoft YaHei&quot;, Arial, sans-serif; margin: 0px; padding: 0px; text-align: center; color: rgb(62, 62, 62); text-transform: none; text-indent: 0px; letter-spacing: normal; clear: both; word-spacing: 0px; white-space: normal; -ms-word-wrap: break-word !important; min-height: 1em; max-width: 100%; box-sizing: border-box !important; widows: 1; font-size-adjust: none; font-stretch: normal; background-color: rgb(255, 255, 255); -webkit-text-stroke-width: 0px; overflow-wrap: break-word;">
    <span style="margin: 0px; padding: 0px; line-height: 25.6px; font-size: 14px; -ms-word-wrap: break-word !important; max-width: 100%; box-sizing: border-box !important; overflow-wrap: break-word;"
          hidden>Leather Battery Wallet</span></p>
<p style="font: 16px/25.6px &quot;Helvetica Neue&quot;, Helvetica, &quot;Hiragino Sans GB&quot;, &quot;Microsoft YaHei&quot;, Arial, sans-serif; margin: 0px; padding: 0px; text-align: center; color: rgb(62, 62, 62); text-transform: none; text-indent: 0px; letter-spacing: normal; clear: both; word-spacing: 0px; white-space: normal; -ms-word-wrap: break-word !important; min-height: 1em; max-width: 100%; box-sizing: border-box !important; widows: 1; font-size-adjust: none; font-stretch: normal; background-color: rgb(255, 255, 255); -webkit-text-stroke-width: 0px; overflow-wrap: break-word;">
    <span style="margin: 0px; padding: 0px; line-height: 25.6px; font-size: 14px; -ms-word-wrap: break-word !important; max-width: 100%; box-sizing: border-box !important; overflow-wrap: break-word;"
          hidden>皮革电池钱包</span></p>
<p style="font: 16px/25.6px &quot;Helvetica Neue&quot;, Helvetica, &quot;Hiragino Sans GB&quot;, &quot;Microsoft YaHei&quot;, Arial, sans-serif; margin: 0px; padding: 0px; text-align: center; color: rgb(62, 62, 62); text-transform: none; text-indent: 0px; letter-spacing: normal; clear: both; word-spacing: 0px; white-space: normal; -ms-word-wrap: break-word !important; min-height: 1em; max-width: 100%; box-sizing: border-box !important; widows: 1; font-size-adjust: none; font-stretch: normal; background-color: rgb(255, 255, 255); -webkit-text-stroke-width: 0px; overflow-wrap: break-word;">
    <img data-ratio="0.5984" data-s="300,640" data-src="/ksyun/2017/03/04/b2753d967ab642ffb2e810f763fde731.jpeg"
         data-type="jpeg" data-w="625"
         style="margin: 0px; padding: 0px; width: auto !important; height: auto !important; visibility: visible !important; -ms-word-wrap: break-word !important; max-width: 100%; box-sizing: border-box !important; overflow-wrap: break-word;"
         src="http://static.poinetech.com/cms/ksyun/2017/03/04/b2753d967ab642ffb2e810f763fde731.jpeg" width="auto"
         hidden></p>
<p style="font: 16px/25.6px &quot;Helvetica Neue&quot;, Helvetica, &quot;Hiragino Sans GB&quot;, &quot;Microsoft YaHei&quot;, Arial, sans-serif; margin: 0px; padding: 0px; color: rgb(62, 62, 62); text-transform: none; text-indent: 0px; letter-spacing: normal; clear: both; word-spacing: 0px; white-space: normal; -ms-word-wrap: break-word !important; min-height: 1em; max-width: 100%; box-sizing: border-box !important; widows: 1; font-size-adjust: none; font-stretch: normal; background-color: rgb(255, 255, 255); -webkit-text-stroke-width: 0px; overflow-wrap: break-word;">
    <br style="margin: 0px; padding: 0px; -ms-word-wrap: break-word !important; max-width: 100%; box-sizing: border-box !important; overflow-wrap: break-word;">
</p>
<p style="font: 16px/25.6px &quot;Helvetica Neue&quot;, Helvetica, &quot;Hiragino Sans GB&quot;, &quot;Microsoft YaHei&quot;, Arial, sans-serif; margin: 0px; padding: 0px; text-align: center; color: rgb(62, 62, 62); text-transform: none; text-indent: 0px; letter-spacing: normal; clear: both; word-spacing: 0px; white-space: normal; -ms-word-wrap: break-word !important; min-height: 1em; max-width: 100%; box-sizing: border-box !important; widows: 1; font-size-adjust: none; font-stretch: normal; background-color: rgb(255, 255, 255); -webkit-text-stroke-width: 0px; overflow-wrap: break-word;">
    <span style="margin: 0px; padding: 0px; line-height: 25.6px; font-size: 14px; -ms-word-wrap: break-word !important; max-width: 100%; box-sizing: border-box !important; overflow-wrap: break-word;"
          hidden>集合现代人对“智能”+“钱包”的想象横空出世,</span></p>
<p style="font: 16px/25.6px &quot;Helvetica Neue&quot;, Helvetica, &quot;Hiragino Sans GB&quot;, &quot;Microsoft YaHei&quot;, Arial, sans-serif; margin: 0px; padding: 0px; text-align: center; color: rgb(62, 62, 62); text-transform: none; text-indent: 0px; letter-spacing: normal; clear: both; word-spacing: 0px; white-space: normal; -ms-word-wrap: break-word !important; min-height: 1em; max-width: 100%; box-sizing: border-box !important; widows: 1; font-size-adjust: none; font-stretch: normal; background-color: rgb(255, 255, 255); -webkit-text-stroke-width: 0px; overflow-wrap: break-word;">
    <span style="margin: 0px; padding: 0px; line-height: 25.6px; font-size: 14px; -ms-word-wrap: break-word !important; max-width: 100%; box-sizing: border-box !important; overflow-wrap: break-word;"
          hidden>并以它的“放荡”惊艳众人!</span></p>
<p style="font: 16px/25.6px &quot;Helvetica Neue&quot;, Helvetica, &quot;Hiragino Sans GB&quot;, &quot;Microsoft YaHei&quot;, Arial, sans-serif; margin: 0px; padding: 0px; text-align: center; color: rgb(62, 62, 62); text-transform: none; text-indent: 0px; letter-spacing: normal; clear: both; word-spacing: 0px; white-space: normal; -ms-word-wrap: break-word !important; min-height: 1em; max-width: 100%; box-sizing: border-box !important; widows: 1; font-size-adjust: none; font-stretch: normal; background-color: rgb(255, 255, 255); -webkit-text-stroke-width: 0px; overflow-wrap: break-word;">
    <span style="margin: 0px; padding: 0px; line-height: 25.6px; font-size: 14px; -ms-word-wrap: break-word !important; max-width: 100%; box-sizing: border-box !important; overflow-wrap: break-word;"
          hidden>将钱包和充电宝完美结合。</span></p>
<p style="font: 16px/25.6px &quot;Helvetica Neue&quot;, Helvetica, &quot;Hiragino Sans GB&quot;, &quot;Microsoft YaHei&quot;, Arial, sans-serif; margin: 0px; padding: 0px; text-align: center; color: rgb(62, 62, 62); text-transform: none; text-indent: 0px; letter-spacing: normal; clear: both; word-spacing: 0px; white-space: normal; -ms-word-wrap: break-word !important; min-height: 1em; max-width: 100%; box-sizing: border-box !important; widows: 1; font-size-adjust: none; font-stretch: normal; background-color: rgb(255, 255, 255); -webkit-text-stroke-width: 0px; overflow-wrap: break-word;">
    <img class="__bg_gif" data-ratio="0.5525" data-src="/ksyun/2017/03/04/b3596db17036440989cebc39267c291c.gif"
         data-type="gif" data-w="400"
         style="margin: 0px; padding: 0px; width: auto !important; height: auto !important; visibility: visible !important; -ms-word-wrap: break-word !important; max-width: 100%; box-sizing: border-box !important; overflow-wrap: break-word;"
         src="http://static.poinetech.com/cms/ksyun/2017/03/04/b3596db17036440989cebc39267c291c.gif" width="auto"
         hidden></p>
<p style="font: 16px/25.6px &quot;Helvetica Neue&quot;, Helvetica, &quot;Hiragino Sans GB&quot;, &quot;Microsoft YaHei&quot;, Arial, sans-serif; margin: 0px; padding: 0px; text-align: center; color: rgb(62, 62, 62); text-transform: none; text-indent: 0px; letter-spacing: normal; clear: both; word-spacing: 0px; white-space: normal; -ms-word-wrap: break-word !important; min-height: 1em; max-width: 100%; box-sizing: border-box !important; widows: 1; font-size-adjust: none; font-stretch: normal; background-color: rgb(255, 255, 255); -webkit-text-stroke-width: 0px; overflow-wrap: break-word;">
    <span style="margin: 0px; padding: 0px; line-height: 25.6px; font-size: 14px; -ms-word-wrap: break-word !important; max-width: 100%; box-sizing: border-box !important; overflow-wrap: break-word;"><br
            style="margin: 0px; padding: 0px; -ms-word-wrap: break-word !important; max-width: 100%; box-sizing: border-box !important; overflow-wrap: break-word;"></span>
</p>
<p style="font: 16px/25.6px &quot;Helvetica Neue&quot;, Helvetica, &quot;Hiragino Sans GB&quot;, &quot;Microsoft YaHei&quot;, Arial, sans-serif; margin: 0px; padding: 0px; text-align: center; color: rgb(62, 62, 62); text-transform: none; text-indent: 0px; letter-spacing: normal; clear: both; word-spacing: 0px; white-space: normal; -ms-word-wrap: break-word !important; min-height: 1em; max-width: 100%; box-sizing: border-box !important; widows: 1; font-size-adjust: none; font-stretch: normal; background-color: rgb(255, 255, 255); -webkit-text-stroke-width: 0px; overflow-wrap: break-word;">
    <span style="margin: 0px; padding: 0px; line-height: 25.6px; font-size: 14px; -ms-word-wrap: break-word !important; max-width: 100%; box-sizing: border-box !important; overflow-wrap: break-word;"
          hidden>不单单是为了实用，</span></p>
<p style="font: 16px/25.6px &quot;Helvetica Neue&quot;, Helvetica, &quot;Hiragino Sans GB&quot;, &quot;Microsoft YaHei&quot;, Arial, sans-serif; margin: 0px; padding: 0px; text-align: center; color: rgb(62, 62, 62); text-transform: none; text-indent: 0px; letter-spacing: normal; clear: both; word-spacing: 0px; white-space: normal; -ms-word-wrap: break-word !important; min-height: 1em; max-width: 100%; box-sizing: border-box !important; widows: 1; font-size-adjust: none; font-stretch: normal; background-color: rgb(255, 255, 255); -webkit-text-stroke-width: 0px; overflow-wrap: break-word;">
    <span style="margin: 0px; padding: 0px; line-height: 25.6px; font-size: 14px; -ms-word-wrap: break-word !important; max-width: 100%; box-sizing: border-box !important; overflow-wrap: break-word;"
          hidden>它的材质也是无法挑剔。</span></p>
<p style="font: 16px/25.6px &quot;Helvetica Neue&quot;, Helvetica, &quot;Hiragino Sans GB&quot;, &quot;Microsoft YaHei&quot;, Arial, sans-serif; margin: 0px; padding: 0px; text-align: center; color: rgb(62, 62, 62); text-transform: none; text-indent: 0px; letter-spacing: normal; clear: both; word-spacing: 0px; white-space: normal; -ms-word-wrap: break-word !important; min-height: 1em; max-width: 100%; box-sizing: border-box !important; widows: 1; font-size-adjust: none; font-stretch: normal; background-color: rgb(255, 255, 255); -webkit-text-stroke-width: 0px; overflow-wrap: break-word;">
    <span style="margin: 0px; padding: 0px; line-height: 25.6px; font-size: 14px; -ms-word-wrap: break-word !important; max-width: 100%; box-sizing: border-box !important; overflow-wrap: break-word;"
          hidden>钱包的皮革来自一家成立百年的皮革公司---Horween</span></p>
<p style="font: 16px/25.6px &quot;Helvetica Neue&quot;, Helvetica, &quot;Hiragino Sans GB&quot;, &quot;Microsoft YaHei&quot;, Arial, sans-serif; margin: 0px; padding: 0px; text-align: center; color: rgb(62, 62, 62); text-transform: none; text-indent: 0px; letter-spacing: normal; clear: both; word-spacing: 0px; white-space: normal; -ms-word-wrap: break-word !important; min-height: 1em; max-width: 100%; box-sizing: border-box !important; widows: 1; font-size-adjust: none; font-stretch: normal; background-color: rgb(255, 255, 255); -webkit-text-stroke-width: 0px; overflow-wrap: break-word;">
    <img data-ratio="0.6578125" data-s="300,640" data-src="/ksyun/2017/03/04/28dddbf623e94b4f8abb860a8621ebd7.jpeg"
         data-type="jpeg" data-w="640"
         style="margin: 0px; padding: 0px; width: auto !important; height: auto !important; visibility: visible !important; -ms-word-wrap: break-word !important; max-width: 100%; box-sizing: border-box !important; overflow-wrap: break-word;"
         src="http://static.poinetech.com/cms/ksyun/2017/03/04/28dddbf623e94b4f8abb860a8621ebd7.jpeg" width="auto"
         hidden></p>
<p style="font: 16px/25.6px &quot;Helvetica Neue&quot;, Helvetica, &quot;Hiragino Sans GB&quot;, &quot;Microsoft YaHei&quot;, Arial, sans-serif; margin: 0px; padding: 0px; text-align: center; color: rgb(62, 62, 62); text-transform: none; text-indent: 0px; letter-spacing: normal; clear: both; word-spacing: 0px; white-space: normal; -ms-word-wrap: break-word !important; min-height: 1em; max-width: 100%; box-sizing: border-box !important; widows: 1; font-size-adjust: none; font-stretch: normal; background-color: rgb(255, 255, 255); -webkit-text-stroke-width: 0px; overflow-wrap: break-word;">
    <span style="margin: 0px; padding: 0px; line-height: 25.6px; font-size: 14px; -ms-word-wrap: break-word !important; max-width: 100%; box-sizing: border-box !important; overflow-wrap: break-word;"></span><br
        style="margin: 0px; padding: 0px; -ms-word-wrap: break-word !important; max-width: 100%; box-sizing: border-box !important; overflow-wrap: break-word;">
</p>
<p style="font: 16px/25.6px &quot;Helvetica Neue&quot;, Helvetica, &quot;Hiragino Sans GB&quot;, &quot;Microsoft YaHei&quot;, Arial, sans-serif; margin: 0px; padding: 0px; text-align: center; color: rgb(62, 62, 62); text-transform: none; text-indent: 0px; letter-spacing: normal; clear: both; word-spacing: 0px; white-space: normal; -ms-word-wrap: break-word !important; min-height: 1em; max-width: 100%; box-sizing: border-box !important; widows: 1; font-size-adjust: none; font-stretch: normal; background-color: rgb(255, 255, 255); -webkit-text-stroke-width: 0px; overflow-wrap: break-word;">
    <span style="margin: 0px; padding: 0px; line-height: 25.6px; font-size: 14px; -ms-word-wrap: break-word !important; max-width: 100%; box-sizing: border-box !important; overflow-wrap: break-word;"
          hidden>钱包不会有刺鼻的气味，</span></p>
<p style="font: 16px/25.6px &quot;Helvetica Neue&quot;, Helvetica, &quot;Hiragino Sans GB&quot;, &quot;Microsoft YaHei&quot;, Arial, sans-serif; margin: 0px; padding: 0px; text-align: center; color: rgb(62, 62, 62); text-transform: none; text-indent: 0px; letter-spacing: normal; clear: both; word-spacing: 0px; white-space: normal; -ms-word-wrap: break-word !important; min-height: 1em; max-width: 100%; box-sizing: border-box !important; widows: 1; font-size-adjust: none; font-stretch: normal; background-color: rgb(255, 255, 255); -webkit-text-stroke-width: 0px; overflow-wrap: break-word;">
    <span style="margin: 0px; padding: 0px; line-height: 25.6px; font-size: 14px; -ms-word-wrap: break-word !important; max-width: 100%; box-sizing: border-box !important; overflow-wrap: break-word;"
          hidden>它的皮质纹理，</span></p>
<p style="font: 16px/25.6px &quot;Helvetica Neue&quot;, Helvetica, &quot;Hiragino Sans GB&quot;, &quot;Microsoft YaHei&quot;, Arial, sans-serif; margin: 0px; padding: 0px; text-align: center; color: rgb(62, 62, 62); text-transform: none; text-indent: 0px; letter-spacing: normal; clear: both; word-spacing: 0px; white-space: normal; -ms-word-wrap: break-word !important; min-height: 1em; max-width: 100%; box-sizing: border-box !important; widows: 1; font-size-adjust: none; font-stretch: normal; background-color: rgb(255, 255, 255); -webkit-text-stroke-width: 0px; overflow-wrap: break-word;">
    <span style="margin: 0px; padding: 0px; line-height: 25.6px; font-size: 14px; -ms-word-wrap: break-word !important; max-width: 100%; box-sizing: border-box !important; overflow-wrap: break-word;"
          hidden>也将随着使用时间变久而越发漂亮。</span></p>
<p style="font: 16px/25.6px &quot;Helvetica Neue&quot;, Helvetica, &quot;Hiragino Sans GB&quot;, &quot;Microsoft YaHei&quot;, Arial, sans-serif; margin: 0px; padding: 0px; text-align: center; color: rgb(62, 62, 62); text-transform: none; text-indent: 0px; letter-spacing: normal; clear: both; word-spacing: 0px; white-space: normal; -ms-word-wrap: break-word !important; min-height: 1em; max-width: 100%; box-sizing: border-box !important; widows: 1; font-size-adjust: none; font-stretch: normal; background-color: rgb(255, 255, 255); -webkit-text-stroke-width: 0px; overflow-wrap: break-word;">
    <img data-ratio="0.8089285714285714" data-s="300,640"
         data-src="/ksyun/2017/03/04/fddbcadbf70740d986fd2a05583ec639.jpeg" data-type="jpeg" data-w="560"
         style="margin: 0px; padding: 0px; width: auto !important; height: auto !important; visibility: visible !important; -ms-word-wrap: break-word !important; max-width: 100%; box-sizing: border-box !important; overflow-wrap: break-word;"
         src="http://static.poinetech.com/cms/ksyun/2017/03/04/fddbcadbf70740d986fd2a05583ec639.jpeg" width="auto"
         hidden></p>
<p style="font: 16px/25.6px &quot;Helvetica Neue&quot;, Helvetica, &quot;Hiragino Sans GB&quot;, &quot;Microsoft YaHei&quot;, Arial, sans-serif; margin: 0px; padding: 0px; text-align: center; color: rgb(62, 62, 62); text-transform: none; text-indent: 0px; letter-spacing: normal; clear: both; word-spacing: 0px; white-space: normal; -ms-word-wrap: break-word !important; min-height: 1em; max-width: 100%; box-sizing: border-box !important; widows: 1; font-size-adjust: none; font-stretch: normal; background-color: rgb(255, 255, 255); -webkit-text-stroke-width: 0px; overflow-wrap: break-word;">
    <span style="margin: 0px; padding: 0px; line-height: 25.6px; font-size: 14px; -ms-word-wrap: break-word !important; max-width: 100%; box-sizing: border-box !important; overflow-wrap: break-word;"></span><span
        style="margin: 0px; padding: 0px; line-height: 25.6px; font-size: 14px; -ms-word-wrap: break-word !important; max-width: 100%; box-sizing: border-box !important; overflow-wrap: break-word;"><br
        style="margin: 0px; padding: 0px; -ms-word-wrap: break-word !important; max-width: 100%; box-sizing: border-box !important; overflow-wrap: break-word;"></span>
</p>
<p style="font: 16px/25.6px &quot;Helvetica Neue&quot;, Helvetica, &quot;Hiragino Sans GB&quot;, &quot;Microsoft YaHei&quot;, Arial, sans-serif; margin: 0px; padding: 0px; text-align: center; color: rgb(62, 62, 62); text-transform: none; text-indent: 0px; letter-spacing: normal; clear: both; word-spacing: 0px; white-space: normal; -ms-word-wrap: break-word !important; min-height: 1em; max-width: 100%; box-sizing: border-box !important; widows: 1; font-size-adjust: none; font-stretch: normal; background-color: rgb(255, 255, 255); -webkit-text-stroke-width: 0px; overflow-wrap: break-word;">
    <span style="margin: 0px; padding: 0px; line-height: 25.6px; font-size: 14px; -ms-word-wrap: break-word !important; max-width: 100%; box-sizing: border-box !important; overflow-wrap: break-word;"
          hidden>为了确保皮革缝制质量，</span></p>
<p style="font: 16px/25.6px &quot;Helvetica Neue&quot;, Helvetica, &quot;Hiragino Sans GB&quot;, &quot;Microsoft YaHei&quot;, Arial, sans-serif; margin: 0px; padding: 0px; text-align: center; color: rgb(62, 62, 62); text-transform: none; text-indent: 0px; letter-spacing: normal; clear: both; word-spacing: 0px; white-space: normal; -ms-word-wrap: break-word !important; min-height: 1em; max-width: 100%; box-sizing: border-box !important; widows: 1; font-size-adjust: none; font-stretch: normal; background-color: rgb(255, 255, 255); -webkit-text-stroke-width: 0px; overflow-wrap: break-word;">
    <span style="margin: 0px; padding: 0px; line-height: 25.6px; font-size: 14px; -ms-word-wrap: break-word !important; max-width: 100%; box-sizing: border-box !important; overflow-wrap: break-word;"
          hidden>就连钱包的亚麻线，</span></p>
<p style="font: 16px/25.6px &quot;Helvetica Neue&quot;, Helvetica, &quot;Hiragino Sans GB&quot;, &quot;Microsoft YaHei&quot;, Arial, sans-serif; margin: 0px; padding: 0px; text-align: center; color: rgb(62, 62, 62); text-transform: none; text-indent: 0px; letter-spacing: normal; clear: both; word-spacing: 0px; white-space: normal; -ms-word-wrap: break-word !important; min-height: 1em; max-width: 100%; box-sizing: border-box !important; widows: 1; font-size-adjust: none; font-stretch: normal; background-color: rgb(255, 255, 255); -webkit-text-stroke-width: 0px; overflow-wrap: break-word;">
    <span style="margin: 0px; padding: 0px; line-height: 25.6px; font-size: 14px; -ms-word-wrap: break-word !important; max-width: 100%; box-sizing: border-box !important; overflow-wrap: break-word;"
          hidden>都选来自法国Barrois的Toulemonde，</span></p>
<p style="font: 16px/25.6px &quot;Helvetica Neue&quot;, Helvetica, &quot;Hiragino Sans GB&quot;, &quot;Microsoft YaHei&quot;, Arial, sans-serif; margin: 0px; padding: 0px; text-align: center; color: rgb(62, 62, 62); text-transform: none; text-indent: 0px; letter-spacing: normal; clear: both; word-spacing: 0px; white-space: normal; -ms-word-wrap: break-word !important; min-height: 1em; max-width: 100%; box-sizing: border-box !important; widows: 1; font-size-adjust: none; font-stretch: normal; background-color: rgb(255, 255, 255); -webkit-text-stroke-width: 0px; overflow-wrap: break-word;">
    <span style="margin: 0px; padding: 0px; line-height: 25.6px; font-size: 14px; -ms-word-wrap: break-word !important; max-width: 100%; box-sizing: border-box !important; overflow-wrap: break-word;"
          hidden>确保钱包坚固耐用。</span></p>
<p style="font: 16px/25.6px &quot;Helvetica Neue&quot;, Helvetica, &quot;Hiragino Sans GB&quot;, &quot;Microsoft YaHei&quot;, Arial, sans-serif; margin: 0px; padding: 0px; text-align: center; color: rgb(62, 62, 62); text-transform: none; text-indent: 0px; letter-spacing: normal; clear: both; word-spacing: 0px; white-space: normal; -ms-word-wrap: break-word !important; min-height: 1em; max-width: 100%; box-sizing: border-box !important; widows: 1; font-size-adjust: none; font-stretch: normal; background-color: rgb(255, 255, 255); -webkit-text-stroke-width: 0px; overflow-wrap: break-word;">
    <img data-ratio="0.8843537414965986" data-s="300,640"
         data-src="/ksyun/2017/03/04/ad7883422ed8410b9c0b972bd93ec147.jpeg" data-type="png" data-w="588"
         style="margin: 0px; padding: 0px; width: auto !important; height: auto !important; visibility: visible !important; -ms-word-wrap: break-word !important; max-width: 100%; box-sizing: border-box !important; overflow-wrap: break-word;"
         src="http://static.poinetech.com/cms/ksyun/2017/03/04/ad7883422ed8410b9c0b972bd93ec147.jpeg" width="auto"
         hidden></p>
<p style="font: 16px/25.6px &quot;Helvetica Neue&quot;, Helvetica, &quot;Hiragino Sans GB&quot;, &quot;Microsoft YaHei&quot;, Arial, sans-serif; margin: 0px; padding: 0px; text-align: center; color: rgb(62, 62, 62); text-transform: none; text-indent: 0px; letter-spacing: normal; clear: both; word-spacing: 0px; white-space: normal; -ms-word-wrap: break-word !important; min-height: 1em; max-width: 100%; box-sizing: border-box !important; widows: 1; font-size-adjust: none; font-stretch: normal; background-color: rgb(255, 255, 255); -webkit-text-stroke-width: 0px; overflow-wrap: break-word;">
    <span style="margin: 0px; padding: 0px; line-height: 25.6px; font-size: 14px; -ms-word-wrap: break-word !important; max-width: 100%; box-sizing: border-box !important; overflow-wrap: break-word;"></span><br
        style="margin: 0px; padding: 0px; -ms-word-wrap: break-word !important; max-width: 100%; box-sizing: border-box !important; overflow-wrap: break-word;">
</p>
<p style="font: 16px/25.6px &quot;Helvetica Neue&quot;, Helvetica, &quot;Hiragino Sans GB&quot;, &quot;Microsoft YaHei&quot;, Arial, sans-serif; margin: 0px; padding: 0px; text-align: center; color: rgb(62, 62, 62); text-transform: none; text-indent: 0px; letter-spacing: normal; clear: both; word-spacing: 0px; white-space: normal; -ms-word-wrap: break-word !important; min-height: 1em; max-width: 100%; box-sizing: border-box !important; widows: 1; font-size-adjust: none; font-stretch: normal; background-color: rgb(255, 255, 255); -webkit-text-stroke-width: 0px;">
    <span style="margin: 0px; padding: 0px; line-height: 25.6px; font-size: 14px; -ms-word-wrap: break-word !important; max-width: 100%; box-sizing: border-box !important; overflow-wrap: break-word;"
          hidden>钱包内置一枚由Panasonic技术支持的</span></p>
<p style="font: 16px/25.6px &quot;Helvetica Neue&quot;, Helvetica, &quot;Hiragino Sans GB&quot;, &quot;Microsoft YaHei&quot;, Arial, sans-serif; margin: 0px; padding: 0px; text-align: center; color: rgb(62, 62, 62); text-transform: none; text-indent: 0px; letter-spacing: normal; clear: both; word-spacing: 0px; white-space: normal; -ms-word-wrap: break-word !important; min-height: 1em; max-width: 100%; box-sizing: border-box !important; widows: 1; font-size-adjust: none; font-stretch: normal; background-color: rgb(255, 255, 255); -webkit-text-stroke-width: 0px;">
    <span style="margin: 0px; padding: 0px; line-height: 25.6px; font-size: 14px; -ms-word-wrap: break-word !important; max-width: 100%; box-sizing: border-box !important; overflow-wrap: break-word;"
          hidden>2400mAh锂离子电池，</span></p>
<p style="font: 16px/25.6px &quot;Helvetica Neue&quot;, Helvetica, &quot;Hiragino Sans GB&quot;, &quot;Microsoft YaHei&quot;, Arial, sans-serif; margin: 0px; padding: 0px; text-align: center; color: rgb(62, 62, 62); text-transform: none; text-indent: 0px; letter-spacing: normal; clear: both; word-spacing: 0px; white-space: normal; -ms-word-wrap: break-word !important; min-height: 1em; max-width: 100%; box-sizing: border-box !important; widows: 1; font-size-adjust: none; font-stretch: normal; background-color: rgb(255, 255, 255); -webkit-text-stroke-width: 0px; overflow-wrap: break-word;">
    <span style="margin: 0px; padding: 0px; line-height: 25.6px; font-size: 14px; -ms-word-wrap: break-word !important; max-width: 100%; box-sizing: border-box !important; overflow-wrap: break-word;"
          hidden>足以让iPhone 6s充饱电一次。</span></p>
<p style="font: 16px/25.6px &quot;Helvetica Neue&quot;, Helvetica, &quot;Hiragino Sans GB&quot;, &quot;Microsoft YaHei&quot;, Arial, sans-serif; margin: 0px; padding: 0px; text-align: center; color: rgb(62, 62, 62); text-transform: none; text-indent: 0px; letter-spacing: normal; clear: both; word-spacing: 0px; white-space: normal; -ms-word-wrap: break-word !important; min-height: 1em; max-width: 100%; box-sizing: border-box !important; widows: 1; font-size-adjust: none; font-stretch: normal; background-color: rgb(255, 255, 255); -webkit-text-stroke-width: 0px; overflow-wrap: break-word;">
    <img class="__bg_gif" data-ratio="0.5525" data-src="/ksyun/2017/03/04/a008f834efca4e1e9c9a21b59c5da8d9.gif"
         data-type="gif" data-w="400"
         style="margin: 0px; padding: 0px; width: auto !important; height: auto !important; visibility: visible !important; -ms-word-wrap: break-word !important; max-width: 100%; box-sizing: border-box !important; overflow-wrap: break-word;"
         src="http://static.poinetech.com/cms/ksyun/2017/03/04/a008f834efca4e1e9c9a21b59c5da8d9.gif" width="auto"
         hidden></p>
<p style="font: 16px/25.6px &quot;Helvetica Neue&quot;, Helvetica, &quot;Hiragino Sans GB&quot;, &quot;Microsoft YaHei&quot;, Arial, sans-serif; margin: 0px; padding: 0px; color: rgb(62, 62, 62); text-transform: none; text-indent: 0px; letter-spacing: normal; clear: both; word-spacing: 0px; white-space: normal; -ms-word-wrap: break-word !important; min-height: 1em; max-width: 100%; box-sizing: border-box !important; widows: 1; font-size-adjust: none; font-stretch: normal; background-color: rgb(255, 255, 255); -webkit-text-stroke-width: 0px; overflow-wrap: break-word;">
    <br style="margin: 0px; padding: 0px; color: rgb(62, 62, 62); line-height: 25.6px; font-size: 16px; white-space: normal; -ms-word-wrap: break-word !important; max-width: 100%; box-sizing: border-box !important; background-color: rgb(255, 255, 255); overflow-wrap: break-word;">
</p>
<p style="font: 16px/25.6px &quot;Helvetica Neue&quot;, Helvetica, &quot;Hiragino Sans GB&quot;, &quot;Microsoft YaHei&quot;, Arial, sans-serif; margin: 0px; padding: 0px; text-align: center; color: rgb(62, 62, 62); text-transform: none; text-indent: 0px; letter-spacing: normal; clear: both; word-spacing: 0px; white-space: normal; -ms-word-wrap: break-word !important; min-height: 1em; max-width: 100%; box-sizing: border-box !important; widows: 1; font-size-adjust: none; font-stretch: normal; background-color: rgb(255, 255, 255); -webkit-text-stroke-width: 0px; overflow-wrap: break-word;">
    <span style="margin: 0px; padding: 0px; line-height: 25.6px; font-size: 14px; -ms-word-wrap: break-word !important; max-width: 100%; box-sizing: border-box !important; overflow-wrap: break-word;"
          hidden>这样的一个钱包，<br
            style="margin: 0px; padding: 0px; -ms-word-wrap: break-word !important; max-width: 100%; box-sizing: border-box !important; overflow-wrap: break-word;"></span>
</p>
<p style="font: 16px/25.6px &quot;Helvetica Neue&quot;, Helvetica, &quot;Hiragino Sans GB&quot;, &quot;Microsoft YaHei&quot;, Arial, sans-serif; margin: 0px; padding: 0px; text-align: center; color: rgb(62, 62, 62); text-transform: none; text-indent: 0px; letter-spacing: normal; clear: both; word-spacing: 0px; white-space: normal; -ms-word-wrap: break-word !important; min-height: 1em; max-width: 100%; box-sizing: border-box !important; widows: 1; font-size-adjust: none; font-stretch: normal; background-color: rgb(255, 255, 255); -webkit-text-stroke-width: 0px; overflow-wrap: break-word;">
    <span style="margin: 0px; padding: 0px; line-height: 25.6px; font-size: 14px; -ms-word-wrap: break-word !important; max-width: 100%; box-sizing: border-box !important; overflow-wrap: break-word;"
          hidden>加上电池的重量，</span></p>
<p style="font: 16px/25.6px &quot;Helvetica Neue&quot;, Helvetica, &quot;Hiragino Sans GB&quot;, &quot;Microsoft YaHei&quot;, Arial, sans-serif; margin: 0px; padding: 0px; text-align: center; color: rgb(62, 62, 62); text-transform: none; text-indent: 0px; letter-spacing: normal; clear: both; word-spacing: 0px; white-space: normal; -ms-word-wrap: break-word !important; min-height: 1em; max-width: 100%; box-sizing: border-box !important; widows: 1; font-size-adjust: none; font-stretch: normal; background-color: rgb(255, 255, 255); -webkit-text-stroke-width: 0px; overflow-wrap: break-word;">
    <span style="margin: 0px; padding: 0px; line-height: 25.6px; font-size: 14px; -ms-word-wrap: break-word !important; max-width: 100%; box-sizing: border-box !important; overflow-wrap: break-word;"
          hidden>它的体重也只有101g！</span></p>
<p style="font: 16px/25.6px &quot;Helvetica Neue&quot;, Helvetica, &quot;Hiragino Sans GB&quot;, &quot;Microsoft YaHei&quot;, Arial, sans-serif; margin: 0px; padding: 0px; text-align: center; color: rgb(62, 62, 62); text-transform: none; text-indent: 0px; letter-spacing: normal; clear: both; word-spacing: 0px; white-space: normal; -ms-word-wrap: break-word !important; min-height: 1em; max-width: 100%; box-sizing: border-box !important; widows: 1; font-size-adjust: none; font-stretch: normal; background-color: rgb(255, 255, 255); -webkit-text-stroke-width: 0px; overflow-wrap: break-word;">
    <span style="margin: 0px; padding: 0px; line-height: 25.6px; font-size: 14px; -ms-word-wrap: break-word !important; max-width: 100%; box-sizing: border-box !important; overflow-wrap: break-word;"
          hidden>堪称完美？</span></p>
<p style="font: 16px/25.6px &quot;Helvetica Neue&quot;, Helvetica, &quot;Hiragino Sans GB&quot;, &quot;Microsoft YaHei&quot;, Arial, sans-serif; margin: 0px; padding: 0px; text-align: center; color: rgb(62, 62, 62); text-transform: none; text-indent: 0px; letter-spacing: normal; clear: both; word-spacing: 0px; white-space: normal; -ms-word-wrap: break-word !important; min-height: 1em; max-width: 100%; box-sizing: border-box !important; widows: 1; font-size-adjust: none; font-stretch: normal; background-color: rgb(255, 255, 255); -webkit-text-stroke-width: 0px; overflow-wrap: break-word;">
    <img data-ratio="0.665625" data-s="300,640" data-src="/ksyun/2017/03/04/25d70e5f6bb64f30806c4961c3c9cdf8.jpeg"
         data-type="jpeg" data-w="640"
         style="margin: 0px; padding: 0px; width: auto !important; height: auto !important; visibility: visible !important; -ms-word-wrap: break-word !important; max-width: 100%; box-sizing: border-box !important; overflow-wrap: break-word;"
         src="http://static.poinetech.com/cms/ksyun/2017/03/04/25d70e5f6bb64f30806c4961c3c9cdf8.jpeg" width="auto"
         hidden></p>
<p style="font: 16px/25.6px &quot;Helvetica Neue&quot;, Helvetica, &quot;Hiragino Sans GB&quot;, &quot;Microsoft YaHei&quot;, Arial, sans-serif; margin: 0px; padding: 0px; color: rgb(62, 62, 62); text-transform: none; text-indent: 0px; letter-spacing: normal; clear: both; word-spacing: 0px; white-space: normal; -ms-word-wrap: break-word !important; min-height: 1em; max-width: 100%; box-sizing: border-box !important; widows: 1; font-size-adjust: none; font-stretch: normal; background-color: rgb(255, 255, 255); -webkit-text-stroke-width: 0px; overflow-wrap: break-word;">
    <br style="margin: 0px; padding: 0px; -ms-word-wrap: break-word !important; max-width: 100%; box-sizing: border-box !important; overflow-wrap: break-word;">
</p>
<p style="font: 16px/25.6px &quot;Helvetica Neue&quot;, Helvetica, &quot;Hiragino Sans GB&quot;, &quot;Microsoft YaHei&quot;, Arial, sans-serif; margin: 0px; padding: 0px; text-align: center; color: rgb(62, 62, 62); text-transform: none; text-indent: 0px; letter-spacing: normal; clear: both; word-spacing: 0px; white-space: normal; -ms-word-wrap: break-word !important; min-height: 1em; max-width: 100%; box-sizing: border-box !important; widows: 1; font-size-adjust: none; font-stretch: normal; background-color: rgb(255, 255, 255); -webkit-text-stroke-width: 0px; overflow-wrap: break-word;">
    <span style="margin: 0px; padding: 0px; line-height: 25.6px; font-size: 14px; -ms-word-wrap: break-word !important; max-width: 100%; box-sizing: border-box !important; overflow-wrap: break-word;"
          hidden>但如果仅仅只是这样，</span></p>
<p style="font: 16px/25.6px &quot;Helvetica Neue&quot;, Helvetica, &quot;Hiragino Sans GB&quot;, &quot;Microsoft YaHei&quot;, Arial, sans-serif; margin: 0px; padding: 0px; text-align: center; color: rgb(62, 62, 62); text-transform: none; text-indent: 0px; letter-spacing: normal; clear: both; word-spacing: 0px; white-space: normal; -ms-word-wrap: break-word !important; min-height: 1em; max-width: 100%; box-sizing: border-box !important; widows: 1; font-size-adjust: none; font-stretch: normal; background-color: rgb(255, 255, 255); -webkit-text-stroke-width: 0px; overflow-wrap: break-word;">
    <span style="margin: 0px; padding: 0px; line-height: 25.6px; font-size: 14px; -ms-word-wrap: break-word !important; max-width: 100%; box-sizing: border-box !important; overflow-wrap: break-word;"
          hidden>也算不上成精？<br
            style="margin: 0px; padding: 0px; -ms-word-wrap: break-word !important; max-width: 100%; box-sizing: border-box !important; overflow-wrap: break-word;"></span>
</p>
<p style="font: 16px/25.6px &quot;Helvetica Neue&quot;, Helvetica, &quot;Hiragino Sans GB&quot;, &quot;Microsoft YaHei&quot;, Arial, sans-serif; margin: 0px; padding: 0px; text-align: center; color: rgb(62, 62, 62); text-transform: none; text-indent: 0px; letter-spacing: normal; clear: both; word-spacing: 0px; white-space: normal; -ms-word-wrap: break-word !important; min-height: 1em; max-width: 100%; box-sizing: border-box !important; widows: 1; font-size-adjust: none; font-stretch: normal; background-color: rgb(255, 255, 255); -webkit-text-stroke-width: 0px; overflow-wrap: break-word;">
    <span style="margin: 0px; padding: 0px; line-height: 25.6px; font-size: 14px; -ms-word-wrap: break-word !important; max-width: 100%; box-sizing: border-box !important; overflow-wrap: break-word;"
          hidden>有意思的才算刚刚开始。<br
            style="margin: 0px; padding: 0px; -ms-word-wrap: break-word !important; max-width: 100%; box-sizing: border-box !important; overflow-wrap: break-word;"></span>
</p>
<p style="font: 16px/25.6px &quot;Helvetica Neue&quot;, Helvetica, &quot;Hiragino Sans GB&quot;, &quot;Microsoft YaHei&quot;, Arial, sans-serif; margin: 0px; padding: 0px; text-align: center; color: rgb(62, 62, 62); text-transform: none; text-indent: 0px; letter-spacing: normal; clear: both; word-spacing: 0px; white-space: normal; -ms-word-wrap: break-word !important; min-height: 1em; max-width: 100%; box-sizing: border-box !important; widows: 1; font-size-adjust: none; font-stretch: normal; background-color: rgb(255, 255, 255); -webkit-text-stroke-width: 0px; overflow-wrap: break-word;">
    <span style="margin: 0px; padding: 0px; line-height: 25.6px; font-size: 14px; -ms-word-wrap: break-word !important; max-width: 100%; box-sizing: border-box !important; overflow-wrap: break-word;"
          hidden>它虽然是钱包，<br
            style="margin: 0px; padding: 0px; -ms-word-wrap: break-word !important; max-width: 100%; box-sizing: border-box !important; overflow-wrap: break-word;"></span>
</p>
<p style="font: 16px/25.6px &quot;Helvetica Neue&quot;, Helvetica, &quot;Hiragino Sans GB&quot;, &quot;Microsoft YaHei&quot;, Arial, sans-serif; margin: 0px; padding: 0px; text-align: center; color: rgb(62, 62, 62); text-transform: none; text-indent: 0px; letter-spacing: normal; clear: both; word-spacing: 0px; white-space: normal; -ms-word-wrap: break-word !important; min-height: 1em; max-width: 100%; box-sizing: border-box !important; widows: 1; font-size-adjust: none; font-stretch: normal; background-color: rgb(255, 255, 255); -webkit-text-stroke-width: 0px; overflow-wrap: break-word;">
    <span style="margin: 0px; padding: 0px; line-height: 25.6px; font-size: 14px; -ms-word-wrap: break-word !important; max-width: 100%; box-sizing: border-box !important; overflow-wrap: break-word;"
          hidden>但却是个守财奴钱包！</span></p>
<p style="font: 16px/25.6px &quot;Helvetica Neue&quot;, Helvetica, &quot;Hiragino Sans GB&quot;, &quot;Microsoft YaHei&quot;, Arial, sans-serif; margin: 0px; padding: 0px; text-align: center; color: rgb(62, 62, 62); text-transform: none; text-indent: 0px; letter-spacing: normal; clear: both; word-spacing: 0px; white-space: normal; -ms-word-wrap: break-word !important; min-height: 1em; max-width: 100%; box-sizing: border-box !important; widows: 1; font-size-adjust: none; font-stretch: normal; background-color: rgb(255, 255, 255); -webkit-text-stroke-width: 0px; overflow-wrap: break-word;">
    <img data-ratio="0.546875" data-s="300,640" data-src="/ksyun/2017/03/04/c5a3c3ee551044058495041fa36b26d6.jpeg"
         data-type="jpeg" data-w="640"
         style="margin: 0px; padding: 0px; width: auto !important; height: auto !important; visibility: visible !important; -ms-word-wrap: break-word !important; max-width: 100%; box-sizing: border-box !important; overflow-wrap: break-word;"
         src="http://static.poinetech.com/cms/ksyun/2017/03/04/c5a3c3ee551044058495041fa36b26d6.jpeg" width="auto"
         hidden></p>
<p style="font: 16px/25.6px &quot;Helvetica Neue&quot;, Helvetica, &quot;Hiragino Sans GB&quot;, &quot;Microsoft YaHei&quot;, Arial, sans-serif; margin: 0px; padding: 0px; color: rgb(62, 62, 62); text-transform: none; text-indent: 0px; letter-spacing: normal; clear: both; word-spacing: 0px; white-space: normal; -ms-word-wrap: break-word !important; min-height: 1em; max-width: 100%; box-sizing: border-box !important; widows: 1; font-size-adjust: none; font-stretch: normal; background-color: rgb(255, 255, 255); -webkit-text-stroke-width: 0px; overflow-wrap: break-word;">
    <br style="margin: 0px; padding: 0px; -ms-word-wrap: break-word !important; max-width: 100%; box-sizing: border-box !important; overflow-wrap: break-word;">
</p>
<p style="font: 16px/25.6px &quot;Helvetica Neue&quot;, Helvetica, &quot;Hiragino Sans GB&quot;, &quot;Microsoft YaHei&quot;, Arial, sans-serif; margin: 0px; padding: 0px; text-align: center; color: rgb(62, 62, 62); text-transform: none; text-indent: 0px; letter-spacing: normal; clear: both; word-spacing: 0px; white-space: normal; -ms-word-wrap: break-word !important; min-height: 1em; max-width: 100%; box-sizing: border-box !important; widows: 1; font-size-adjust: none; font-stretch: normal; background-color: rgb(255, 255, 255); -webkit-text-stroke-width: 0px; overflow-wrap: break-word;">
    <span style="margin: 0px; padding: 0px; line-height: 25.6px; font-size: 14px; -ms-word-wrap: break-word !important; max-width: 100%; box-sizing: border-box !important; overflow-wrap: break-word;"
          hidden>为何这么说？<br
            style="margin: 0px; padding: 0px; -ms-word-wrap: break-word !important; max-width: 100%; box-sizing: border-box !important; overflow-wrap: break-word;"></span>
</p>
<p style="font: 16px/25.6px &quot;Helvetica Neue&quot;, Helvetica, &quot;Hiragino Sans GB&quot;, &quot;Microsoft YaHei&quot;, Arial, sans-serif; margin: 0px; padding: 0px; text-align: center; color: rgb(62, 62, 62); text-transform: none; text-indent: 0px; letter-spacing: normal; clear: both; word-spacing: 0px; white-space: normal; -ms-word-wrap: break-word !important; min-height: 1em; max-width: 100%; box-sizing: border-box !important; widows: 1; font-size-adjust: none; font-stretch: normal; background-color: rgb(255, 255, 255); -webkit-text-stroke-width: 0px; overflow-wrap: break-word;">
    <span style="margin: 0px; padding: 0px; line-height: 25.6px; font-size: 14px; -ms-word-wrap: break-word !important; max-width: 100%; box-sizing: border-box !important; overflow-wrap: break-word;"
          hidden>因为它可以跟手机APP-Zaim连接，</span></p>
<p style="font: 16px/25.6px &quot;Helvetica Neue&quot;, Helvetica, &quot;Hiragino Sans GB&quot;, &quot;Microsoft YaHei&quot;, Arial, sans-serif; margin: 0px; padding: 0px; text-align: center; color: rgb(62, 62, 62); text-transform: none; text-indent: 0px; letter-spacing: normal; clear: both; word-spacing: 0px; white-space: normal; -ms-word-wrap: break-word !important; min-height: 1em; max-width: 100%; box-sizing: border-box !important; widows: 1; font-size-adjust: none; font-stretch: normal; background-color: rgb(255, 255, 255); -webkit-text-stroke-width: 0px; overflow-wrap: break-word;">
    <span style="margin: 0px; padding: 0px; line-height: 25.6px; font-size: 14px; -ms-word-wrap: break-word !important; max-width: 100%; box-sizing: border-box !important; overflow-wrap: break-word;"
          hidden>让你的钱包进入“省钱模式”！</span></p>
<p style="font: 16px/25.6px &quot;Helvetica Neue&quot;, Helvetica, &quot;Hiragino Sans GB&quot;, &quot;Microsoft YaHei&quot;, Arial, sans-serif; margin: 0px; padding: 0px; text-align: center; color: rgb(62, 62, 62); text-transform: none; text-indent: 0px; letter-spacing: normal; clear: both; word-spacing: 0px; white-space: normal; -ms-word-wrap: break-word !important; min-height: 1em; max-width: 100%; box-sizing: border-box !important; widows: 1; font-size-adjust: none; font-stretch: normal; background-color: rgb(255, 255, 255); -webkit-text-stroke-width: 0px; overflow-wrap: break-word;">
    <img class="__bg_gif" data-ratio="0.5625" data-src="/ksyun/2017/03/04/cdd02fece4f8403f84fb048ba78f5b7d.gif"
         data-type="gif" data-w="400"
         style="margin: 0px; padding: 0px; width: auto !important; height: auto !important; visibility: visible !important; -ms-word-wrap: break-word !important; max-width: 100%; box-sizing: border-box !important; overflow-wrap: break-word;"
         src="http://static.poinetech.com/cms/ksyun/2017/03/04/cdd02fece4f8403f84fb048ba78f5b7d.gif" width="auto"
         hidden></p>
<p style="font: 16px/25.6px &quot;Helvetica Neue&quot;, Helvetica, &quot;Hiragino Sans GB&quot;, &quot;Microsoft YaHei&quot;, Arial, sans-serif; margin: 0px; padding: 0px; text-align: center; color: rgb(62, 62, 62); text-transform: none; text-indent: 0px; letter-spacing: normal; clear: both; word-spacing: 0px; white-space: normal; -ms-word-wrap: break-word !important; min-height: 1em; max-width: 100%; box-sizing: border-box !important; widows: 1; font-size-adjust: none; font-stretch: normal; background-color: rgb(255, 255, 255); -webkit-text-stroke-width: 0px; overflow-wrap: break-word;">
    <span style="margin: 0px; padding: 0px; line-height: 25.6px; font-size: 14px; -ms-word-wrap: break-word !important; max-width: 100%; box-sizing: border-box !important; overflow-wrap: break-word;"></span><br
        style="margin: 0px; padding: 0px; -ms-word-wrap: break-word !important; max-width: 100%; box-sizing: border-box !important; overflow-wrap: break-word;">
</p>
<p style="font: 16px/25.6px &quot;Helvetica Neue&quot;, Helvetica, &quot;Hiragino Sans GB&quot;, &quot;Microsoft YaHei&quot;, Arial, sans-serif; margin: 0px; padding: 0px; text-align: center; color: rgb(62, 62, 62); text-transform: none; text-indent: 0px; letter-spacing: normal; clear: both; word-spacing: 0px; white-space: normal; -ms-word-wrap: break-word !important; min-height: 1em; max-width: 100%; box-sizing: border-box !important; widows: 1; font-size-adjust: none; font-stretch: normal; background-color: rgb(255, 255, 255); -webkit-text-stroke-width: 0px; overflow-wrap: break-word;">
    <span style="margin: 0px; padding: 0px; line-height: 25.6px; font-size: 14px; -ms-word-wrap: break-word !important; max-width: 100%; box-sizing: border-box !important; overflow-wrap: break-word;"
          hidden>一旦模式启动，<br
            style="margin: 0px; padding: 0px; -ms-word-wrap: break-word !important; max-width: 100%; box-sizing: border-box !important; overflow-wrap: break-word;"></span>
</p>
<p style="font: 16px/25.6px &quot;Helvetica Neue&quot;, Helvetica, &quot;Hiragino Sans GB&quot;, &quot;Microsoft YaHei&quot;, Arial, sans-serif; margin: 0px; padding: 0px; text-align: center; color: rgb(62, 62, 62); text-transform: none; text-indent: 0px; letter-spacing: normal; clear: both; word-spacing: 0px; white-space: normal; -ms-word-wrap: break-word !important; min-height: 1em; max-width: 100%; box-sizing: border-box !important; widows: 1; font-size-adjust: none; font-stretch: normal; background-color: rgb(255, 255, 255); -webkit-text-stroke-width: 0px; overflow-wrap: break-word;">
    <span style="margin: 0px; padding: 0px; line-height: 25.6px; font-size: 14px; -ms-word-wrap: break-word !important; max-width: 100%; box-sizing: border-box !important; overflow-wrap: break-word;"
          hidden>当你缺钱伸手时，它会立马逃跑！</span></p>
<p style="font: 16px/25.6px &quot;Helvetica Neue&quot;, Helvetica, &quot;Hiragino Sans GB&quot;, &quot;Microsoft YaHei&quot;, Arial, sans-serif; margin: 0px; padding: 0px; text-align: center; color: rgb(62, 62, 62); text-transform: none; text-indent: 0px; letter-spacing: normal; clear: both; word-spacing: 0px; white-space: normal; -ms-word-wrap: break-word !important; min-height: 1em; max-width: 100%; box-sizing: border-box !important; widows: 1; font-size-adjust: none; font-stretch: normal; background-color: rgb(255, 255, 255); -webkit-text-stroke-width: 0px; overflow-wrap: break-word;">
    <span style="margin: 0px; padding: 0px; line-height: 25.6px; font-size: 14px; -ms-word-wrap: break-word !important; max-width: 100%; box-sizing: border-box !important; overflow-wrap: break-word;"
          hidden>借助钱包上的小轮子以及内置的传感器，</span></p>
<p style="font: 16px/25.6px &quot;Helvetica Neue&quot;, Helvetica, &quot;Hiragino Sans GB&quot;, &quot;Microsoft YaHei&quot;, Arial, sans-serif; margin: 0px; padding: 0px; text-align: center; color: rgb(62, 62, 62); text-transform: none; text-indent: 0px; letter-spacing: normal; clear: both; word-spacing: 0px; white-space: normal; -ms-word-wrap: break-word !important; min-height: 1em; max-width: 100%; box-sizing: border-box !important; widows: 1; font-size-adjust: none; font-stretch: normal; background-color: rgb(255, 255, 255); -webkit-text-stroke-width: 0px; overflow-wrap: break-word;">
    <span style="margin: 0px; padding: 0px; line-height: 25.6px; font-size: 14px; -ms-word-wrap: break-word !important; max-width: 100%; box-sizing: border-box !important; overflow-wrap: break-word;"
          hidden>更可以轻松地规避障碍物。</span></p>
<p style="font: 16px/25.6px &quot;Helvetica Neue&quot;, Helvetica, &quot;Hiragino Sans GB&quot;, &quot;Microsoft YaHei&quot;, Arial, sans-serif; margin: 0px; padding: 0px; text-align: center; color: rgb(62, 62, 62); text-transform: none; text-indent: 0px; letter-spacing: normal; clear: both; word-spacing: 0px; white-space: normal; -ms-word-wrap: break-word !important; min-height: 1em; max-width: 100%; box-sizing: border-box !important; widows: 1; font-size-adjust: none; font-stretch: normal; background-color: rgb(255, 255, 255); -webkit-text-stroke-width: 0px; overflow-wrap: break-word;">
    <img class="__bg_gif" data-ratio="0.5625" data-src="/ksyun/2017/03/04/5e9da17d126c46cb802ecf1377168a93.gif"
         data-type="gif" data-w="400"
         style="margin: 0px; padding: 0px; width: auto !important; height: auto !important; visibility: visible !important; -ms-word-wrap: break-word !important; max-width: 100%; box-sizing: border-box !important; overflow-wrap: break-word;"
         src="http://static.poinetech.com/cms/ksyun/2017/03/04/5e9da17d126c46cb802ecf1377168a93.gif" width="auto"
         hidden></p>
<p style="font: 16px/25.6px &quot;Helvetica Neue&quot;, Helvetica, &quot;Hiragino Sans GB&quot;, &quot;Microsoft YaHei&quot;, Arial, sans-serif; margin: 0px; padding: 0px; color: rgb(62, 62, 62); text-transform: none; text-indent: 0px; letter-spacing: normal; clear: both; word-spacing: 0px; white-space: normal; -ms-word-wrap: break-word !important; min-height: 1em; max-width: 100%; box-sizing: border-box !important; widows: 1; font-size-adjust: none; font-stretch: normal; background-color: rgb(255, 255, 255); -webkit-text-stroke-width: 0px; overflow-wrap: break-word;">
    <br style="margin: 0px; padding: 0px; -ms-word-wrap: break-word !important; max-width: 100%; box-sizing: border-box !important; overflow-wrap: break-word;">
</p>
<p style="font: 16px/25.6px &quot;Helvetica Neue&quot;, Helvetica, &quot;Hiragino Sans GB&quot;, &quot;Microsoft YaHei&quot;, Arial, sans-serif; margin: 0px; padding: 0px; text-align: center; color: rgb(62, 62, 62); text-transform: none; text-indent: 0px; letter-spacing: normal; clear: both; word-spacing: 0px; white-space: normal; -ms-word-wrap: break-word !important; min-height: 1em; max-width: 100%; box-sizing: border-box !important; widows: 1; font-size-adjust: none; font-stretch: normal; background-color: rgb(255, 255, 255); -webkit-text-stroke-width: 0px; overflow-wrap: break-word;">
    <span style="margin: 0px; padding: 0px; line-height: 25.6px; font-size: 14px; -ms-word-wrap: break-word !important; max-width: 100%; box-sizing: border-box !important; overflow-wrap: break-word;"
          hidden>如果强行抓它</span></p>
<p style="font: 16px/25.6px &quot;Helvetica Neue&quot;, Helvetica, &quot;Hiragino Sans GB&quot;, &quot;Microsoft YaHei&quot;, Arial, sans-serif; margin: 0px; padding: 0px; text-align: center; color: rgb(62, 62, 62); text-transform: none; text-indent: 0px; letter-spacing: normal; clear: both; word-spacing: 0px; white-space: normal; -ms-word-wrap: break-word !important; min-height: 1em; max-width: 100%; box-sizing: border-box !important; widows: 1; font-size-adjust: none; font-stretch: normal; background-color: rgb(255, 255, 255); -webkit-text-stroke-width: 0px; overflow-wrap: break-word;">
    <span style="margin: 0px; padding: 0px; line-height: 25.6px; font-size: 14px; -ms-word-wrap: break-word !important; max-width: 100%; box-sizing: border-box !important; overflow-wrap: break-word;"
          hidden>它还会挣扎呼救，发出警告！</span></p>
<p style="font: 16px/25.6px &quot;Helvetica Neue&quot;, Helvetica, &quot;Hiragino Sans GB&quot;, &quot;Microsoft YaHei&quot;, Arial, sans-serif; margin: 0px; padding: 0px; text-align: center; color: rgb(62, 62, 62); text-transform: none; text-indent: 0px; letter-spacing: normal; clear: both; word-spacing: 0px; white-space: normal; -ms-word-wrap: break-word !important; min-height: 1em; max-width: 100%; box-sizing: border-box !important; widows: 1; font-size-adjust: none; font-stretch: normal; background-color: rgb(255, 255, 255); -webkit-text-stroke-width: 0px; overflow-wrap: break-word;">
    <span style="margin: 0px; padding: 0px; line-height: 25.6px; font-size: 14px; -ms-word-wrap: break-word !important; max-width: 100%; box-sizing: border-box !important; overflow-wrap: break-word;"
          hidden>如果你还是一意孤行，</span></p>
<p style="font: 16px/25.6px &quot;Helvetica Neue&quot;, Helvetica, &quot;Hiragino Sans GB&quot;, &quot;Microsoft YaHei&quot;, Arial, sans-serif; margin: 0px; padding: 0px; text-align: center; color: rgb(62, 62, 62); text-transform: none; text-indent: 0px; letter-spacing: normal; clear: both; word-spacing: 0px; white-space: normal; -ms-word-wrap: break-word !important; min-height: 1em; max-width: 100%; box-sizing: border-box !important; widows: 1; font-size-adjust: none; font-stretch: normal; background-color: rgb(255, 255, 255); -webkit-text-stroke-width: 0px; overflow-wrap: break-word;">
    <span style="margin: 0px; padding: 0px; line-height: 25.6px; font-size: 14px; -ms-word-wrap: break-word !important; max-width: 100%; box-sizing: border-box !important; overflow-wrap: break-word;"
          hidden>它甚至会打电话给你的家人。<br
            style="margin: 0px; padding: 0px; -ms-word-wrap: break-word !important; max-width: 100%; box-sizing: border-box !important; overflow-wrap: break-word;"></span>
</p>
<p style="font: 16px/25.6px &quot;Helvetica Neue&quot;, Helvetica, &quot;Hiragino Sans GB&quot;, &quot;Microsoft YaHei&quot;, Arial, sans-serif; margin: 0px; padding: 0px; text-align: center; color: rgb(62, 62, 62); text-transform: none; text-indent: 0px; letter-spacing: normal; clear: both; word-spacing: 0px; white-space: normal; -ms-word-wrap: break-word !important; min-height: 1em; max-width: 100%; box-sizing: border-box !important; widows: 1; font-size-adjust: none; font-stretch: normal; background-color: rgb(255, 255, 255); -webkit-text-stroke-width: 0px; overflow-wrap: break-word;">
    <img class="__bg_gif" data-ratio="0.5625" data-src="/ksyun/2017/03/04/784721be9ea24735bf094913e72375cd.gif"
         data-type="gif" data-w="400"
         style="margin: 0px; padding: 0px; width: auto !important; height: auto !important; visibility: visible !important; -ms-word-wrap: break-word !important; max-width: 100%; box-sizing: border-box !important; overflow-wrap: break-word;"
         src="http://static.poinetech.com/cms/ksyun/2017/03/04/784721be9ea24735bf094913e72375cd.gif" width="auto"
         hidden></p>
<p style="font: 16px/25.6px &quot;Helvetica Neue&quot;, Helvetica, &quot;Hiragino Sans GB&quot;, &quot;Microsoft YaHei&quot;, Arial, sans-serif; margin: 0px; padding: 0px; color: rgb(62, 62, 62); text-transform: none; text-indent: 0px; letter-spacing: normal; clear: both; word-spacing: 0px; white-space: normal; -ms-word-wrap: break-word !important; min-height: 1em; max-width: 100%; box-sizing: border-box !important; widows: 1; font-size-adjust: none; font-stretch: normal; background-color: rgb(255, 255, 255); -webkit-text-stroke-width: 0px; overflow-wrap: break-word;">
    <br style="margin: 0px; padding: 0px; -ms-word-wrap: break-word !important; max-width: 100%; box-sizing: border-box !important; overflow-wrap: break-word;">
</p>
<p style="font: 16px/25.6px &quot;Helvetica Neue&quot;, Helvetica, &quot;Hiragino Sans GB&quot;, &quot;Microsoft YaHei&quot;, Arial, sans-serif; margin: 0px; padding: 0px; text-align: center; color: rgb(62, 62, 62); text-transform: none; text-indent: 0px; letter-spacing: normal; clear: both; word-spacing: 0px; white-space: normal; -ms-word-wrap: break-word !important; min-height: 1em; max-width: 100%; box-sizing: border-box !important; widows: 1; font-size-adjust: none; font-stretch: normal; background-color: rgb(255, 255, 255); -webkit-text-stroke-width: 0px; overflow-wrap: break-word;">
    <span style="margin: 0px; padding: 0px; line-height: 25.6px; font-size: 14px; -ms-word-wrap: break-word !important; max-width: 100%; box-sizing: border-box !important; overflow-wrap: break-word;"
          hidden>之后</span></p>
<p style="font: 16px/25.6px &quot;Helvetica Neue&quot;, Helvetica, &quot;Hiragino Sans GB&quot;, &quot;Microsoft YaHei&quot;, Arial, sans-serif; margin: 0px; padding: 0px; text-align: center; color: rgb(62, 62, 62); text-transform: none; text-indent: 0px; letter-spacing: normal; clear: both; word-spacing: 0px; white-space: normal; -ms-word-wrap: break-word !important; min-height: 1em; max-width: 100%; box-sizing: border-box !important; widows: 1; font-size-adjust: none; font-stretch: normal; background-color: rgb(255, 255, 255); -webkit-text-stroke-width: 0px; overflow-wrap: break-word;">
    <span style="margin: 0px; padding: 0px; line-height: 25.6px; font-size: 14px; -ms-word-wrap: break-word !important; max-width: 100%; box-sizing: border-box !important; overflow-wrap: break-word;"
          hidden>.....<br
            style="margin: 0px; padding: 0px; -ms-word-wrap: break-word !important; max-width: 100%; box-sizing: border-box !important; overflow-wrap: break-word;"></span>
</p>
<p style="font: 16px/25.6px &quot;Helvetica Neue&quot;, Helvetica, &quot;Hiragino Sans GB&quot;, &quot;Microsoft YaHei&quot;, Arial, sans-serif; margin: 0px; padding: 0px; text-align: center; color: rgb(62, 62, 62); text-transform: none; text-indent: 0px; letter-spacing: normal; clear: both; word-spacing: 0px; white-space: normal; -ms-word-wrap: break-word !important; min-height: 1em; max-width: 100%; box-sizing: border-box !important; widows: 1; font-size-adjust: none; font-stretch: normal; background-color: rgb(255, 255, 255); -webkit-text-stroke-width: 0px; overflow-wrap: break-word;">
    <span style="margin: 0px; padding: 0px; line-height: 25.6px; font-size: 14px; -ms-word-wrap: break-word !important; max-width: 100%; box-sizing: border-box !important; overflow-wrap: break-word;"
          hidden>控制不住自己的双手？</span></p>
<p style="font: 16px/25.6px &quot;Helvetica Neue&quot;, Helvetica, &quot;Hiragino Sans GB&quot;, &quot;Microsoft YaHei&quot;, Arial, sans-serif; margin: 0px; padding: 0px; text-align: center; color: rgb(62, 62, 62); text-transform: none; text-indent: 0px; letter-spacing: normal; clear: both; word-spacing: 0px; white-space: normal; -ms-word-wrap: break-word !important; min-height: 1em; max-width: 100%; box-sizing: border-box !important; widows: 1; font-size-adjust: none; font-stretch: normal; background-color: rgb(255, 255, 255); -webkit-text-stroke-width: 0px; overflow-wrap: break-word;">
    <span style="margin: 0px; padding: 0px; line-height: 25.6px; font-size: 14px; -ms-word-wrap: break-word !important; max-width: 100%; box-sizing: border-box !important; overflow-wrap: break-word;"
          hidden>想来还有些可怕！</span></p>
<p style="font: 16px/25.6px &quot;Helvetica Neue&quot;, Helvetica, &quot;Hiragino Sans GB&quot;, &quot;Microsoft YaHei&quot;, Arial, sans-serif; margin: 0px; padding: 0px; text-align: center; color: rgb(62, 62, 62); text-transform: none; text-indent: 0px; letter-spacing: normal; clear: both; word-spacing: 0px; white-space: normal; -ms-word-wrap: break-word !important; min-height: 1em; max-width: 100%; box-sizing: border-box !important; widows: 1; font-size-adjust: none; font-stretch: normal; background-color: rgb(255, 255, 255); -webkit-text-stroke-width: 0px; overflow-wrap: break-word;">
    <span style="margin: 0px; padding: 0px; line-height: 25.6px; font-size: 14px; -ms-word-wrap: break-word !important; max-width: 100%; box-sizing: border-box !important; overflow-wrap: break-word;"></span>
</p>
<p style="font: 16px/25.6px &quot;Helvetica Neue&quot;, Helvetica, &quot;Hiragino Sans GB&quot;, &quot;Microsoft YaHei&quot;, Arial, sans-serif; margin: 0px; padding: 0px; text-align: center; color: rgb(62, 62, 62); text-transform: none; text-indent: 0px; letter-spacing: normal; clear: both; word-spacing: 0px; white-space: normal; -ms-word-wrap: break-word !important; min-height: 1em; max-width: 100%; box-sizing: border-box !important; widows: 1; font-size-adjust: none; font-stretch: normal; background-color: rgb(255, 255, 255); -webkit-text-stroke-width: 0px; overflow-wrap: break-word;">
    <img data-ratio="0.8227272727272727" data-s="300,640"
         data-src="/ksyun/2017/03/04/fd9f2b1eb5aa4ae2ac056a45bd66a6fe.jpeg" data-type="jpeg" data-w="220"
         style="margin: 0px; padding: 0px; width: auto !important; height: auto !important; visibility: visible !important; -ms-word-wrap: break-word !important; max-width: 100%; box-sizing: border-box !important; overflow-wrap: break-word;"
         src="http://static.poinetech.com/cms/ksyun/2017/03/04/fd9f2b1eb5aa4ae2ac056a45bd66a6fe.jpeg" width="auto"
         hidden></p>
<p><img data-ratio="1.25" data-s="300,640" data-src="/ksyun/2017/03/04/daed4d7e1ac14bd8b55980c7ee4d55c3.jpeg"
        data-type="jpeg" data-w="600"
        style="width: auto !important; height: auto !important; text-align: center; color: rgb(62, 62, 62); line-height: 25.6px; font-size: 16px; white-space: normal; visibility: visible !important; -ms-word-wrap: break-word !important; box-sizing: border-box !important; background-color: rgb(255, 255, 255);"
        src="http://static.poinetech.com/cms/ksyun/2017/03/04/daed4d7e1ac14bd8b55980c7ee4d55c3.jpeg" width="auto"
        hidden></p>
</body>
</html>